application: jarshack
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /image
  static_dir: image

- url: /.*
  script: main.py

builtins:
- datastore_admin: on
